In [1]:
import pandas as pd

In [2]:
df= pd.read_csv('data/survey_results_public.csv', index_col= 'Respondent')
schema_df=  pd.read_csv('data/survey_results_schema.csv', index_col= 'Column')

In [3]:
pd.set_option('display.max_columns', 85)
pd.set_option('display.max_rows', 85)

In [4]:
df.head()

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [5]:
sample_df= df[['Age', 'LanguageWorkedWith', 'ConvertedComp']]

In [6]:
sample_df.dropna(axis= 'index', how= 'any', inplace= True)

C:\Users\USER\AppData\Local\Temp\ipykernel_17616\4136304120.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample_df.dropna(axis= 'index', how= 'any', inplace= True)

In [7]:
sample_df.head()

,Age,LanguageWorkedWith,ConvertedComp
Respondent,,,
3,28.0,HTML/CSS,8820.0
4,22.0,C;C++;C#;Python;SQL,61000.0
6,28.0,Java;R;SQL,366420.0
9,23.0,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;P...,95179.0
13,28.0,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...,90000.0

In [8]:
filt= (sample_df['Age'] >= 18) & (sample_df['Age'] <= 37)

In [9]:
sample_df= sample_df.loc[filt,['Age','LanguageWorkedWith', 'ConvertedComp']]

In [10]:
sample_df

,Age,LanguageWorkedWith,ConvertedComp
Respondent,,,
3,28.0,HTML/CSS,8820.0
4,22.0,C;C++;C#;Python;SQL,61000.0
6,28.0,Java;R;SQL,366420.0
9,23.0,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;P...,95179.0
13,28.0,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...,90000.0
...,...,...,...
88876,23.0,Bash/Shell/PowerShell;C#;HTML/CSS;Java;Python;...,180000.0
88878,26.0,HTML/CSS;JavaScript;Scala;TypeScript,130000.0
88879,34.0,Bash/Shell/PowerShell;C++;Python,82488.0
88881,37.0,Bash/Shell/PowerShell;Go;HTML/CSS;Java;JavaScr...,68745.0
88883,33.0,Go;HTML/CSS;Java;JavaScript;Other(s):,22915.0

In [11]:
Age_grp= sample_df.groupby('Age')

In [12]:
#Age_grp['ConvertedComp'].agg('median')
median_salary_by_age= Age_grp['ConvertedComp'].median()
median_salary_by_age

Age
18.0      13750.0
19.0      14506.0
20.0      16000.0
20.9      41244.0
21.0      19236.0
22.0      23769.5
22.5      11040.0
23.0      29442.0
23.5      12228.0
24.0      33583.0
24.5      88610.0
24.8       8400.0
25.0      37837.0
26.0      41820.0
26.3      31403.0
26.5      68000.0
27.0      46272.0
28.0      49163.0
28.5      50868.0
29.0      52934.0
29.5      12228.0
30.0      55985.5
30.8      66424.0
31.0      62316.0
31.4     272700.0
31.5    1069000.0
32.0      65000.0
33.0      68020.5
33.6     101748.0
34.0      69420.5
35.0      74474.0
36.0      77022.0
36.8      15600.0
37.0      78237.5
Name: ConvertedComp, dtype: float64

In [13]:
python_users_by_age= Age_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())
python_users_by_age.head()

Age
18.0     68
19.0    148
20.0    238
20.9      0
21.0    475
Name: LanguageWorkedWith, dtype: int64

In [14]:
python_users_df= pd.DataFrame({'MedianSalary': median_salary_by_age, 'PythonUsers': python_users_by_age})

In [15]:
python_users_df.head()

      MedianSalary  PythonUsers
Age
18.0       13750.0           68
19.0       14506.0          148
20.0       16000.0          238
20.9       41244.0            0
21.0       19236.0          475

In [16]:
python_users_df = python_users_df[python_users_df['PythonUsers'] > 0]

In [17]:
python_users_df

      MedianSalary  PythonUsers
Age
18.0       13750.0           68
19.0       14506.0          148
20.0       16000.0          238
21.0       19236.0          475
22.0       23769.5          870
23.0       29442.0         1215
23.5       12228.0            1
24.0       33583.0         1397
24.5       88610.0            1
25.0       37837.0         1428
26.0       41820.0         1346
26.3       31403.0            1
26.5       68000.0            1
27.0       46272.0         1359
28.0       49163.0         1301
28.5       50868.0            1
29.0       52934.0         1149
30.0       55985.5         1200
31.0       62316.0          951
31.4      272700.0            1
31.5     1069000.0            1
32.0       65000.0          934
33.0       68020.5          768
34.0       69420.5          733
35.0       74474.0          745
36.0       77022.0          594
37.0       78237.5          544

In [18]:
Js_users_by_age= Age_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('JavaScript').sum())
Js_users_df= pd.DataFrame({'MedianSalary': median_salary_by_age, 'JavaScript_Users': Js_users_by_age})
Js_users_df = Js_users_df[Js_users_df['JavaScript_Users'] > 0]
Js_users_df

      MedianSalary  JavaScript_Users
Age
18.0       13750.0               129
19.0       14506.0               242
20.0       16000.0               420
21.0       19236.0               754
22.0       23769.5              1289
22.5       11040.0                 1
23.0       29442.0              1888
23.5       12228.0                 2
24.0       33583.0              2256
24.5       88610.0                 2
24.8        8400.0                 1
25.0       37837.0              2460
26.0       41820.0              2350
26.3       31403.0                 1
26.5       68000.0                 1
27.0       46272.0              2417
28.0       49163.0              2421
29.0       52934.0              2205
29.5       12228.0                 1
30.0       55985.5              2235
30.8       66424.0                 1
31.0       62316.0              1671
31.4      272700.0                 1
31.5     1069000.0                 2
32.0       65000.0              1701
33.0       68020.5              1514
33.6      101748.0                 1
34.0       69420.5              1338
35.0       74474.0              1311
36.0       77022.0              1133
37.0       78237.5              1021

In [19]:
result_df= { }

In [20]:
result_df= pd.DataFrame(result_df)

In [21]:
result_df['All_dev']= median_salary_by_age

In [22]:
result_df['Python'] = python_users_df['MedianSalary']

In [23]:
result_df['JavaScript']= Js_users_df['MedianSalary']

In [24]:
result_df.dropna(axis= 'index', how= 'any', inplace=True)

In [25]:
#result_df.reset_index(inplace=True)

In [26]:
result_df.drop(index= [23.5, 24.5, 26.3, 26.5, 31.4, 31.5])

      All_dev   Python  JavaScript
Age
18.0  13750.0  13750.0     13750.0
19.0  14506.0  14506.0     14506.0
20.0  16000.0  16000.0     16000.0
21.0  19236.0  19236.0     19236.0
22.0  23769.5  23769.5     23769.5
23.0  29442.0  29442.0     29442.0
24.0  33583.0  33583.0     33583.0
25.0  37837.0  37837.0     37837.0
26.0  41820.0  41820.0     41820.0
27.0  46272.0  46272.0     46272.0
28.0  49163.0  49163.0     49163.0
29.0  52934.0  52934.0     52934.0
30.0  55985.5  55985.5     55985.5
31.0  62316.0  62316.0     62316.0
32.0  65000.0  65000.0     65000.0
33.0  68020.5  68020.5     68020.5
34.0  69420.5  69420.5     69420.5
35.0  74474.0  74474.0     74474.0
36.0  77022.0  77022.0     77022.0
37.0  78237.5  78237.5     78237.5

In [27]:
result_df.reset_index(inplace=True)

In [28]:
result_df.head(13)

     Age  All_dev   Python  JavaScript
0   18.0  13750.0  13750.0     13750.0
1   19.0  14506.0  14506.0     14506.0
2   20.0  16000.0  16000.0     16000.0
3   21.0  19236.0  19236.0     19236.0
4   22.0  23769.5  23769.5     23769.5
5   23.0  29442.0  29442.0     29442.0
6   23.5  12228.0  12228.0     12228.0
7   24.0  33583.0  33583.0     33583.0
8   24.5  88610.0  88610.0     88610.0
9   25.0  37837.0  37837.0     37837.0
10  26.0  41820.0  41820.0     41820.0
11  26.3  31403.0  31403.0     31403.0
12  26.5  68000.0  68000.0     68000.0